name: Deploy to AWS ECR

on:
  push:
    branches:
      - main  # Runs only when pushing to main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        env:
          AWS_REGION: us-east-1  # Change to your AWS region
          ECR_REPOSITORY: aaronshemtov/urlshortener
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t $ECR_REPOSITORY:latest . --push
